<!DOCTYPE html>
<html lang="en">
<head>
  <!-- other meta stuff -->
  <!-- References to external basic CSS file -->
  <link href="styles/style.css" rel="stylesheet">
  <link href="styles/enhancements2.css" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Rancho&amp;effect=shadow-multiple|3d-float' rel='stylesheet'>
  <meta charset="utf-8">
  <meta name="description" content="index">
  <meta name="keywords" content="index">
  <meta name="author" content="Sithumini Sandarekha Amarawansha Gamage">
  <script src="scripts/enhancements.js"></script>
  <title>Home</title>
</head>
<body>
  <article>
    <header class="head1"></header>
    <nav>
      <ul>
        <li>
          <a href="index.php">Home</a>
        </li>
        <li>
          <a href="jobs.php">Jobs</a>
        </li>
        <li>
          <a href=".html">Job Application</a>
        </li>
        <li>
          <a href="about.php">About Me</a>
        </li>
        <li>
          <a href="enhancements1.php">Enhancements 1</a>
        </li>
        <li>
          <a href="enhancements2.php">Enhancements 2</a>
        </li>
      </ul>
    </nav>
