
<?php
include './header.inc';
?>

<nav>
      <ul>
        <li>
          <a href="index.php">Home</a>
        </li>
        <li>
          <a href="jobs.php">Jobs</a>
        </li>
        <li>
          <a href="apply.php">Job Application</a>
        </li>
        <li>
          <a href="manage.php">Manage</a>
        </li>
        <li>
          <a href="about.php">About Me</a>
        </li>
        <li>
          <a href="enhancements1.php">Enhancements 1</a>
        </li>
        <li>
          <a href="enhancements2.php">Enhancements 2</a>
        </li>
      </ul>
</nav>